### ISSUE TITLE
Feature request: English documentation

### ISSUE THREAD

**Issue by ghost** [CallMePixelMan/ask_lib#4]
Hi, I like the idea of this library and was wondering if I could add an English (US) translation of the README and documentation.

In the future, you could add the option of language.

**Comment by CallMePixelMan** [comment]
Hi,

Thank you for your interest, I will probably do a rewrite of the library soon (probably next week) with english documentation and README too, as I made this a long ago with some bad practices.

Thanks again :)

**Comment by ghost** [comment]
Yeah! I'll close this issue then :)

**Comment by CallMePixelMan** [comment]
Hello, I worked a lot today to add tests, CI and documentation. I hope you'll like the changes, version got bumped to 2.0.1, and python version to 3.8!

**Comment by ghost** [comment]
Looking good! 🚀
